#!/usr/bin/node
const minimist = require('minimist')
const arg = minimist(process.argv.slice(2))
const fs = require('fs')
const path = arg.path

function build(path) {
    fs.exists(path, (ex) => {
        if (!ex)
            console.error(`'path' file does not exist.`), process.exit(1)
        fs.readFile(arg.path, (e, v) => {
            console.log(e, v.toString())
        })
    })
}

if (typeof path !== ('string' || 'array'))
    console.error(`Invalid 'path' value.`), process.exit(1)

if (typeof path === 'array')
    path.forEach(e => {
        build(e)
    });
else
    build(path)